dist: trusty
sudo: false
language: node_js
node_js:
- 12
after_success:
- "./node_modules/.bin/codecov"
addons:
  sonarcloud:
    organization: "wayfair"
    token:
      secure: Nu85f+oAoIb5Sq663FNWNJ2T/IZbNkIUYJpIWGpVAaNaaYw/pohS9jsxf1z4Z3II/ma1OJSDQUvkxV9FzaTVzFRVxTJ0ngnVKe5sxvh5K6UfPLqeDCZ+yL9Vu3Vad32VuObk+FIlcM5XfTwiq5JW5ne4tRmnGUYT/fa2HvGQ0Dr3ntk/z897H+2H/XCu69edoconK4LI3qIXBBxGNz+a4yqCbh4azRb27rIDGZXqPynCXfLaePhliTYsN/z2CLDoXdPJFvmpYktCq5+0l9kxNoMUNU9khqclFMXo0uUZt90ESjERWpAb/vdRELu+8M35AgYaadTy8CMW3NFqpJ/qvcTLgAO8sAQuq58vjgHRZuK6mRutL7BLCOdQkeGNXXEXC1V83yqxTBp5/UAbQnNG8c3BR6vQH87DcoPM3qgJQ3esdUO1Qyx8V/bdO/Ylcf3sgNXHTR34LPjL9yKvDVLMIYJLogIi/1uhuAmMUxzKDuNGjHRenruNpB28xe9UZ++Qc+djSepgb5aLmdXoUijGw2Gck3y7d7nLNwG+zkEcaq9ifM8CVUsAHbEek7HkVfGNakcx2AdMXng74BoUTLOaTsEQOZyRZISnnBeZsdiVby8IK9joXH3sMLVTT8nhyreGF3EKoPnshVMsaK3nSt5b+roPpVhKYhX1SYDTAJW+6Es=

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
deploy:
  provider: npm
  email: jsopensource@wayfair.com
  api_key:
    secure: EP1QvdDYjS8si7BpTs96Uz/atftKJVKyFTgh+WSKLcLjRt4boCSJvEZ49EgAG9OWy4NU2I1CDyK0Z7Illrd6rPfWipJdLUFZjlKQoeG0zymCM7Xe+UdK/sD4ODQsC1N1OfssaMFO1JDT4LWJxPZyycIoaXaJW2pnzoNVbkHzhBMNRT04KnJY4d6YXzNQr2bKUlyR2n1EkJA9Hdhhph9WNwS0agH0ddWJbJL4rIoAvWmbITqvuUhH+o6M9I9xlG25r5q3SMT4z7G5HRJt9KTirflUiJQgfOoFzJe9hVDH78HHAClBcBwnHYKNs5eo0R9iZmCOcLRTvP+v5rETB7VjV09kWq1QY7PapZduT8sCZqOCLiIVJo68bZ3RvS8AbSGUAiMMiwlfIGJcJCPTwnujUrnsigNcd0n/uL4XEYxOY5gRBBw62DktzuHglY9xWRFKWltId0kwP9jIaKGgQnAYJCfGV145injRiyTJGB+T9GBmydvEPl9L49eBNWDbg5c5oUQ7Gn4SXwXPY7GeCKjAL8t+0NcMif7xW88ot8lezc0HDPP+pRCTbhDM0smew9uMQlZFFCQLgR1PCmNBdPhhCJfmNkpskXj6HA3/eOGxThkoid+4k7gdF9gVriDIpW79XPctofxLI1taeo/BHyrejr3YBTFISLSGSWGZjPMvvLo=
  on:
    tags: true
    repo: wayfair/dociql
    branch: master
