swagger: 2.0
info:
  version: 1.0.0
  title: Sprockets and springs API
  description: >-
    Covering all your needs for sprockets and springs.
  contact:
    name: Sprocket!
    url: https://sprocketsprings.biz
    email: post@sprocketsprings.biz
basePath: /api/v1
consumes:
  - application/json
produces:
  - application/json
paths:
  /sprockets:
    get:
      summary: Get list of sprockets
      description: >-
        This method returns all your sprockets. No exceptions, even Tiny Timmy is returned.
      operationId: getSprockets
      responses:
        200:
          description: A list of sprockets
          schema:
            type: array
            items:
              $ref: '#/definitions/Sprocket'
          
    post:
      summary: Create a new sprocket
      description: >-
        Use this method to create a new sprocket. Make sure it is a good sprocket. Remember what that bad one did to Uncle Jim.
      operationId: createSprocket
      parameters:
        - name: sprocket
          in: body
          description: The sprocket definition
          required: true
          schema:
            $ref: '#/definitions/NewSprocket'
      responses:
        '200':
          description: The new sprocket
          schema:
            $ref: '#/definitions/Sprocket'
  '/sprockets/{id}':
    get:
      summary: Get a specific sprocket
      description: >-
        Use this method when you need just that one special sprocket in your life. You will get one, and only one.
      operationId: getSprocket
      parameters:
        - name: id
          in: path
          description: numerical id of sprocket
          required: true
          type: integer
      responses:
        '200':
          description: Details of the sprocket
          schema:
            $ref: '#/definitions/Sprocket'
    post:
      summary: Update sprocket
      description: >-
        This is the method to use when you down on your luck and created a sprocket with the wrong specification.
      operationId: updateSprocket
      parameters:
        - name: id
          in: path
          description: numerical id of sprocket
          required: true
          type: integer
        - name: sprocket
          in: body
          description: Correct definition of sprocket
          required: true
          schema:
            $ref: '#/definitions/Sprocket'
      responses:
        '200':
          description: The newly updated sprocket definition
          schema:
            $ref: '#/definitions/Sprocket'
definitions:
  Sprocket:
    allOf:
      - $ref: '#/definitions/NewSprocket'
      - type: object
        required:
          - id
        properties:
          id:
            type: integer
            format: int32
            example: 201
  NewSprocket:
    type: object
    required:
      - name
      - radius
      - teeth
    properties:
      name:
        type: string
        example: My magical sprocket
      radius:
        type: float
        example: 12.0
      teeth:
        type: int
        example: 22
      description:
        type: string
        example: My dearest little sprocket. How I cherish it.